server {
    listen 80;              # Tells Nginx to listen on port 80
    server_name localhost;  # Defines the server name
    root /usr/share/nginx/html;  # Sets the document root directory where files are served from
    index index.html;       # Defines the default file to serve when a directory is requested

    location / {
        try_files $uri $uri/ /index.html;  # Key configuration for SPAs like Angular
    }
}